version: '3.1'
services:
  db:
    image: mysql
    container_name: personalbudget_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - personalbudget_data:/var/lib/mysql

volumes:
  personalbudget_data: